"""Keysight InfiniiVision oscilloscope core runtime."""

from .capabilities import ScopeCapabilities, capabilities_for_model
from .channel import (
    ChannelController,
    parse_channel_coupling,
    parse_channel_display,
    parse_channel_impedance,
    parse_channel_units,
)
from .display import AnnotationState, DisplayController, DisplayPersistence, parse_display_label
from .idn import IDN, detect_series, parse_idn
from .measurements import MeasurementController, MeasurementResult
from .operations import (
    AcquisitionCheckRequest,
    CaptureRequest,
    MeasureLogRequest,
    MeasureRequest,
    MeasureSweepRequest,
    OperationResult,
    SmokeRequest,
    run_acquisition_check,
    run_capture,
    run_doctor,
    run_measure_log,
    run_measure,
    run_measure_sweep,
    run_smoke,
)
from .planning import (
    OperationPlan,
    plan_acquisition_check,
    plan_capture,
    plan_doctor,
    plan_measure,
    plan_measure_sweep,
    plan_smoke,
)
from .run_config import (
    ResolvedRunConfig,
    RunModeOptions,
    open_scope_for_run,
    require_resource,
    resolve_resource,
    resolve_run_mode,
)
from .screenshot import ScreenshotCapture, ScreenshotController
from .scope import KeysightScope
from .status import SystemErrorEntry, parse_system_error
from .timebase import TimebaseController
from .trigger import (
    DelayTriggerController,
    DelayTriggerState,
    EdgeBurstTriggerController,
    EdgeBurstTriggerState,
    EdgeTriggerController,
    EdgeTriggerCouplingController,
    EdgeTriggerCouplingState,
    EdgeTriggerExternalLevelController,
    EdgeTriggerExternalLevelState,
    EdgeTriggerLevelController,
    EdgeTriggerLevelState,
    EdgeTriggerRejectController,
    EdgeTriggerRejectState,
    EdgeTriggerSlopeController,
    EdgeTriggerSlopeState,
    EdgeTriggerSourceController,
    EdgeTriggerSourceState,
    EdgeTriggerState,
    ExternalTriggerRangeController,
    ExternalTriggerRangeState,
    ExternalTriggerProbeController,
    ExternalTriggerProbeState,
    ExternalTriggerSettingsController,
    ExternalTriggerSettingsState,
    ExternalTriggerUnitsController,
    ExternalTriggerUnitsState,
    GlitchTriggerController,
    GlitchTriggerState,
    OrTriggerController,
    OrTriggerState,
    PatternTriggerController,
    PatternTriggerState,
    RuntTriggerController,
    RuntTriggerState,
    SetupHoldTriggerController,
    SetupHoldTriggerState,
    TransitionTriggerController,
    TransitionTriggerState,
    TriggerHfRejectController,
    TriggerNoiseRejectController,
    TriggerRejectState,
    TriggerSweepController,
    TriggerSweepState,
    TriggerWaitConfig,
    TriggerWaitResult,
    TvTriggerController,
    TvTriggerState,
)
from .waveform import MultiChannelWaveformCapture, WaveformCapture, WaveformPreamble

__all__ = [
    "ChannelController",
    "DisplayController",
    "AnnotationState",
    "DisplayPersistence",
    "DelayTriggerController",
    "DelayTriggerState",
    "EdgeBurstTriggerController",
    "EdgeBurstTriggerState",
    "EdgeTriggerController",
    "EdgeTriggerCouplingController",
    "EdgeTriggerCouplingState",
    "EdgeTriggerExternalLevelController",
    "EdgeTriggerExternalLevelState",
    "EdgeTriggerLevelController",
    "EdgeTriggerLevelState",
    "EdgeTriggerRejectController",
    "EdgeTriggerRejectState",
    "EdgeTriggerSlopeController",
    "EdgeTriggerSlopeState",
    "EdgeTriggerSourceController",
    "EdgeTriggerSourceState",
    "EdgeTriggerState",
    "ExternalTriggerRangeController",
    "ExternalTriggerRangeState",
    "ExternalTriggerProbeController",
    "ExternalTriggerProbeState",
    "ExternalTriggerSettingsController",
    "ExternalTriggerSettingsState",
    "ExternalTriggerUnitsController",
    "ExternalTriggerUnitsState",
    "GlitchTriggerController",
    "GlitchTriggerState",
    "OrTriggerController",
    "OrTriggerState",
    "PatternTriggerController",
    "PatternTriggerState",
    "RuntTriggerController",
    "RuntTriggerState",
    "SetupHoldTriggerController",
    "SetupHoldTriggerState",
    "TransitionTriggerController",
    "TransitionTriggerState",
    "TriggerHfRejectController",
    "TriggerNoiseRejectController",
    "TriggerRejectState",
    "TriggerSweepController",
    "TriggerSweepState",
    "TriggerWaitConfig",
    "TriggerWaitResult",
    "TvTriggerController",
    "TvTriggerState",
    "IDN",
    "KeysightScope",
    "MeasurementController",
    "MeasurementResult",
    "MultiChannelWaveformCapture",
    "OperationPlan",
    "OperationResult",
    "ResolvedRunConfig",
    "RunModeOptions",
    "CaptureRequest",
    "MeasureLogRequest",
    "MeasureRequest",
    "MeasureSweepRequest",
    "SmokeRequest",
    "AcquisitionCheckRequest",
    "ScreenshotCapture",
    "ScreenshotController",
    "ScopeCapabilities",
    "SystemErrorEntry",
    "TimebaseController",
    "WaveformCapture",
    "WaveformPreamble",
    "capabilities_for_model",
    "detect_series",
    "parse_channel_display",
    "parse_channel_coupling",
    "parse_channel_impedance",
    "parse_channel_units",
    "parse_display_label",
    "parse_idn",
    "parse_system_error",
    "resolve_run_mode",
    "resolve_resource",
    "require_resource",
    "open_scope_for_run",
    "plan_capture",
    "plan_doctor",
    "plan_measure",
    "plan_measure_sweep",
    "plan_smoke",
    "plan_acquisition_check",
    "run_capture",
    "run_doctor",
    "run_measure_log",
    "run_measure",
    "run_measure_sweep",
    "run_smoke",
    "run_acquisition_check",
]

__version__ = "0.1.0"
