"""Deterministic hardware-free backend for agent workflows."""

from __future__ import annotations

import binascii
from dataclasses import dataclass, field
import math
import re
import struct
from typing import Any, Sequence
import zlib

from .capabilities import capabilities_for_model
from .errors import BackendClosedError, KeysightScopeError


class SimulatorBackendError(KeysightScopeError):
    """Raised when the simulator receives unsupported SCPI."""


_SUPPORTED_WAVEFORM_POINTS = (1000, 5000, 10000)
_INVALID_MEASUREMENT_SENTINEL = "9.9E+37"
_SIGNAL_FREQUENCY_HZ = 1000.0
_SIGNAL_SHAPES = frozenset(("sine", "square", "ramp", "dc", "noise"))
_TIMING_MEASUREMENT_ITEMS = frozenset(
    (
        "frequency",
        "period",
        "x_at_max",
        "x_at_min",
        "rise_time",
        "fall_time",
        "positive_width",
        "negative_width",
        "duty_cycle",
        "negative_duty_cycle",
        "positive_edges",
        "negative_edges",
        "positive_pulses",
        "negative_pulses",
        "time_at_edge",
        "time_at_value",
    )
)
_PAIR_MEASUREMENT_ITEMS = frozenset(("phase", "delay"))


def simulator_idn(model: str) -> str:
    """Return a deterministic IDN string for a simulated model."""

    return f"KEYSIGHT TECHNOLOGIES,{model},SIM000000,07.20"


@dataclass(frozen=True)
class SimulatedSignal:
    """Nominal signal generated by one simulated analog channel."""

    shape: str = "sine"
    frequency_hz: float = _SIGNAL_FREQUENCY_HZ
    vpp_v: float = 0.5
    offset_v: float = 0.0
    phase_deg: float = 0.0
    noise_rms_v: float = 0.0

    def __post_init__(self) -> None:
        shape = self.shape.strip().lower()
        if shape not in _SIGNAL_SHAPES:
            supported = ", ".join(sorted(_SIGNAL_SHAPES))
            raise SimulatorBackendError(
                f"Unsupported simulator signal shape {self.shape!r}; "
                f"expected one of: {supported}."
            )
        values = (
            self.frequency_hz,
            self.vpp_v,
            self.offset_v,
            self.phase_deg,
            self.noise_rms_v,
        )
        if not all(math.isfinite(value) for value in values):
            raise SimulatorBackendError("Simulator signal values must be finite.")
        if self.frequency_hz < 0:
            raise SimulatorBackendError("Simulator signal frequency must be non-negative.")
        if self.vpp_v < 0:
            raise SimulatorBackendError("Simulator signal Vpp must be non-negative.")
        if self.noise_rms_v < 0:
            raise SimulatorBackendError("Simulator signal noise must be non-negative.")
        object.__setattr__(self, "shape", shape)


@dataclass
class SimulatorBackend:
    """Small oscilloscope simulator that records SCPI command order."""

    model: str = "DSOX4024A"
    resource_name: str | None = None
    strict_unknown_commands: bool = True
    system_errors: list[str] = field(default_factory=list)
    query_overrides: dict[str, str] = field(default_factory=dict)
    binary_overrides: dict[str, Sequence[Any]] = field(default_factory=dict)
    write_failures: dict[str, Exception] = field(default_factory=dict)
    query_failures: dict[str, Exception] = field(default_factory=dict)
    binary_failures: dict[str, Exception] = field(default_factory=dict)
    history: list[str] = field(default_factory=list)
    backend: str = "Keysight simulator"
    timeout: int | None = 2000
    closed: bool = False
    channel_display: dict[int, bool] = field(default_factory=dict)
    channel_scale: dict[int, float] = field(default_factory=dict)
    channel_offset: dict[int, float] = field(default_factory=dict)
    channel_coupling: dict[int, str] = field(default_factory=dict)
    channel_probe: dict[int, float] = field(default_factory=dict)
    channel_bandwidth_limit: dict[int, bool] = field(default_factory=dict)
    waveform_source: int = 1
    waveform_format: str = "BYTE"
    waveform_points: int = 1000
    waveform_byte_order: str = "MSBFirst"
    waveform_unsigned: bool = True
    hardcopy_inksaver: bool = False
    acquisition_type: str = "NORMal"
    acquisition_count: int = 8
    sample_rate_hz: float = 5e9
    memory_depth_points: int = 1000000

    run_state: str = "stopped"
    timebase_scale: float = 1e-3
    timebase_position: float = 0.0
    trigger_source: int = 1
    trigger_mode: str = "EDGE"
    trigger_level: float = 0.0
    trigger_slope: str = "POSitive"
    trigger_holdoff: float = 100e-9
    marker_mode: str = "OFF"
    marker_source: int = 1
    marker_x1: float = 0.0
    marker_x2: float = 1e-3
    marker_y1: float = 0.0
    marker_y2: float = 0.5
    measurement_source: int = 1
    measurement_statistics_mode: str = "ALL"
    measurement_statistics_items: list[str] = field(default_factory=list)
    setup_targets: dict[str, str] = field(default_factory=dict)
    fft_functions: dict[int, dict[str, Any]] = field(default_factory=dict)
    invalid_measurement_channels: set[int] = field(default_factory=set)
    signals: dict[int, SimulatedSignal] = field(default_factory=dict)
    trigger_alternate_count: int = 0

    def __post_init__(self) -> None:
        if self.resource_name is None:
            self.resource_name = f"SIM::{self.model}::INSTR"
        self._capabilities = capabilities_for_model(self.model)
        self.system_errors = list(self.system_errors)
        self.signals = {
            self._validate_channel(channel): _coerce_simulated_signal(signal)
            for channel, signal in self.signals.items()
        }

    def write(self, command: str) -> None:
        """Record and apply a simple SCPI write."""

        self._ensure_open()
        self.history.append(command)
        self._raise_configured_failure(self.write_failures, command)
        upper = command.upper()
        if upper in {":RUN", ":STOP", ":SINGLE"}:
            self.run_state = {"RUN": "running", "STOP": "stopped", "SINGLE": "single"}[upper[1:]]
        elif upper == ":TFORCE":
            # :TFORce forces one trigger event; record but do not change simulated state.
            pass
        elif upper.startswith(":WAVEFORM:SOURCE CHANNEL"):
            self.waveform_source = self._validate_channel(
                int(command.rsplit("CHANnel", 1)[1])
            )
        elif upper == ":WAVEFORM:FORMAT BYTE":
            self.waveform_format = "BYTE"
        elif upper == ":WAVEFORM:FORMAT WORD":
            self.waveform_format = "WORD"
        elif upper.startswith(":WAVEFORM:BYTEORDER "):
            self.waveform_byte_order = command.rsplit(" ", 1)[1]
        elif upper.startswith(":WAVEFORM:UNSIGNED "):
            self.waveform_unsigned = upper.endswith(" ON")
        elif upper.startswith(":WAVEFORM:POINTS "):
            points = int(command.rsplit(" ", 1)[1])
            if points not in _SUPPORTED_WAVEFORM_POINTS:
                if self.strict_unknown_commands:
                    raise SimulatorBackendError(
                        f"Unsupported simulator waveform point count: {points}"
                    )
                points = 1000
            self.waveform_points = points
        elif upper.startswith(":HARDCOPY:INKSAVER "):
            self.hardcopy_inksaver = upper.endswith(" ON")
        elif upper.startswith(":ACQUIRE:TYPE "):
            self.acquisition_type = command.rsplit(" ", 1)[1]
        elif upper.startswith(":ACQUIRE:COUNT "):
            self.acquisition_count = int(command.rsplit(" ", 1)[1])
        elif upper.startswith(":TIMEBASE:SCALE "):
            self.timebase_scale = float(command.rsplit(" ", 1)[1])
        elif upper.startswith(":TIMEBASE:POSITION "):
            self.timebase_position = float(command.rsplit(" ", 1)[1])
        elif upper.startswith(":TRIGGER:MODE "):
            self.trigger_mode = command.rsplit(" ", 1)[1]
        elif upper.startswith(":TRIGGER:EDGE:SOURCE CHANNEL"):
            self.trigger_source = self._validate_channel(
                int(command.rsplit("CHANnel", 1)[1])
            )
        elif upper.startswith(":TRIGGER:EDGE:LEVEL "):
            self.trigger_level = float(command.rsplit(" ", 1)[1])
        elif upper.startswith(":TRIGGER:EDGE:SLOPE "):
            self.trigger_slope = command.rsplit(" ", 1)[1]
        elif upper.startswith(":TRIGGER:HOLDOFF "):
            self.trigger_holdoff = _parse_scpi_number(command.split(" ", 1)[1])
        elif upper.startswith(":TRIGGER:HOLDOFF:RANDOM "):
            pass
        elif upper.startswith(":MARKER:MODE "):
            self.marker_mode = command.rsplit(" ", 1)[1].upper()
        elif upper.startswith(":MARKER:X1Y1SOURCE CHANNEL"):
            self.marker_source = self._validate_channel(int(command.rsplit("CHANnel", 1)[1]))
        elif upper.startswith(":MARKER:X2Y2SOURCE CHANNEL"):
            self.marker_source = self._validate_channel(int(command.rsplit("CHANnel", 1)[1]))
        elif upper.startswith(":MARKER:X1POSITION "):
            value = _parse_scpi_number(command.split(" ", 1)[1])
            self._queue_marker_range_error(value)
            self.marker_x1 = value
        elif upper.startswith(":MARKER:X2POSITION "):
            value = _parse_scpi_number(command.split(" ", 1)[1])
            self._queue_marker_range_error(value)
            self.marker_x2 = value
        elif upper.startswith(":MARKER:Y1POSITION "):
            value = _parse_scpi_number(command.split(" ", 1)[1])
            self._queue_marker_y_range_error(value)
            self.marker_y1 = value
        elif upper.startswith(":MARKER:Y2POSITION "):
            value = _parse_scpi_number(command.split(" ", 1)[1])
            self._queue_marker_y_range_error(value)
            self.marker_y2 = value
        elif upper == ":MEASURE:CLEAR":
            self.measurement_statistics_items.clear()
        elif upper.startswith(":MEASURE:SOURCE CHANNEL"):
            self.measurement_source = self._validate_channel(int(command.rsplit("CHANnel", 1)[1]))
        elif upper.startswith(":MEASURE:STATISTICS:COUNT "):
            pass
        elif upper == ":MEASURE:STATISTICS:RESET":
            pass
        elif upper.startswith(":MEASURE:STATISTICS "):
            self.measurement_statistics_mode = command.rsplit(" ", 1)[1].upper()
        elif self._apply_measurement_install(command):
            pass
        elif upper.startswith(":AUTOSCALE"):
            pass
        elif upper.startswith(":SAVE:SETUP "):
            self.setup_targets[command.split(" ", 1)[1]] = "saved"
        elif upper.startswith(":RECALL:SETUP "):
            self.setup_targets.setdefault(command.split(" ", 1)[1], "recalled")
        elif self._apply_fft_write(command):
            pass
        elif not self._apply_channel_write(command):
            self._handle_unknown("write", command)

    def query(self, command: str) -> str:
        """Record one query and return a deterministic response."""

        self._ensure_open()
        self.history.append(command)
        self._raise_configured_failure(self.query_failures, command)
        if command in self.query_overrides:
            return self.query_overrides[command]
        upper = command.upper()
        if upper == "*IDN?":
            return simulator_idn(self.model)
        if upper == ":SYSTEM:ERROR?":
            if self.system_errors:
                return self.system_errors.pop(0)
            return '+0,"No error"'
        if upper == ":WAVEFORM:PREAMBLE?":
            return self._waveform_preamble()
        if upper == ":HARDCOPY:INKSAVER?":
            return "1" if self.hardcopy_inksaver else "0"
        if upper == ":ACQUIRE:TYPE?":
            return self.acquisition_type
        if upper == ":ACQUIRE:SRATE:ANALOG?":
            return f"{self.sample_rate_hz:.6E}"
        if upper == ":ACQUIRE:POINTS:ANALOG?":
            return str(self.memory_depth_points)
        if upper == ":ACQUIRE:COUNT?":
            return str(self.acquisition_count)
        if upper == ":TIMEBASE:SCALE?":
            return f"{self.timebase_scale:.12g}"
        if upper == ":TIMEBASE:POSITION?":
            return f"{self.timebase_position:.12g}"
        if upper == ":TRIGGER:EDGE:SOURCE?":
            return f"CHANnel{self.trigger_source}"
        if upper == ":TRIGGER:EDGE:LEVEL?":
            return f"{self.trigger_level:.12g}"
        if upper == ":TRIGGER:EDGE:SLOPE?":
            return self.trigger_slope
        if upper == ":TRIGGER:HOLDOFF?":
            return f"{self.trigger_holdoff:.12g}"
        if upper == ":MARKER:MODE?":
            return self.marker_mode
        if upper == ":MARKER:X1POSITION?":
            return f"{self.marker_x1:.12g}"
        if upper == ":MARKER:X2POSITION?":
            return f"{self.marker_x2:.12g}"
        if upper == ":MARKER:Y1POSITION?":
            return f"{self.marker_y1:.12g}"
        if upper == ":MARKER:Y2POSITION?":
            return f"{self.marker_y2:.12g}"
        if upper == ":MARKER:XDELTA?":
            return f"{(self.marker_x2 - self.marker_x1):.12g}"
        if upper == ":MARKER:YDELTA?":
            return f"{(self.marker_y2 - self.marker_y1):.12g}"
        if upper == ":MARKER:DYDX?":
            dx = self.marker_x2 - self.marker_x1
            return "9.9E+37" if dx == 0 else f"{((self.marker_y2 - self.marker_y1) / dx):.12g}"
        if upper == ":MEASURE:RESULTS?":
            return self._measurement_statistics_results()
        fft_response = self._query_fft(command)
        if fft_response is not None:
            return fft_response
        if upper.startswith(":MEASURE:") or upper.startswith(":MEASURE?"):
            return self._measurement_value(command)
        channel_response = self._query_channel(command)
        if channel_response is not None:
            return channel_response
        return self._handle_unknown("query", command)

    def read_raw(self) -> bytes:
        """Return empty raw bytes; current CLI uses binary queries instead."""

        self._ensure_open()
        return b""

    def query_binary_values(self, command: str, **kwargs: Any) -> Sequence[Any]:
        """Record one binary query and return waveform or PNG bytes."""

        self._ensure_open()
        self.history.append(command)
        self._raise_configured_failure(self.binary_failures, command)
        if command in self.binary_overrides:
            return self.binary_overrides[command]
        if command.upper().startswith(":DISPLAY:DATA?"):
            return tuple(_simulated_screenshot_png(self.model, white_background=self.hardcopy_inksaver))
        if not command.upper().startswith(":WAVEFORM:DATA?"):
            return self._handle_unknown("binary query", command)
        self._validate_waveform_points()
        if not self.channel_display.get(self.waveform_source, True):
            raise SimulatorBackendError(
                f"Cannot capture CH{self.waveform_source}: channel display is off."
            )
        if self.trigger_slope.upper() in {"ALTERNATE", "ALT"}:
            self.trigger_alternate_count += 1
        if kwargs.get("datatype") == "H":
            return tuple(
                self._encode_word_sample(self._waveform_voltage_at_index(index))
                for index in range(self.waveform_points)
            )
        return tuple(
            self._encode_byte_sample(self._waveform_voltage_at_index(index))
            for index in range(self.waveform_points)
        )

    def set_timeout(self, timeout_ms: int | None) -> None:
        """Set simulated timeout."""

        self._ensure_open()
        self.timeout = timeout_ms

    def close(self) -> None:
        """Close the simulated session."""

        self.closed = True

    def _ensure_open(self) -> None:
        if self.closed:
            raise BackendClosedError("Simulator backend is closed.")

    def _queue_marker_range_error(self, value: float) -> None:
        visible_half_span = self.timebase_scale * 4.5
        if abs(value - self.timebase_position) > visible_half_span:
            self.system_errors.append('-222,"Data out of range"')

    def _queue_marker_y_range_error(self, value: float) -> None:
        scale = self.channel_scale.get(self.marker_source, 1.0)
        offset = self.channel_offset.get(self.marker_source, 0.0)
        visible_half_span = scale * 4.0
        if abs(value - offset) > visible_half_span:
            self.system_errors.append('-222,"Data out of range"')

    def _raise_configured_failure(
        self, failures: dict[str, Exception], command: str
    ) -> None:
        exc = failures.get(command)
        if exc is not None:
            raise exc

    def _handle_unknown(self, operation: str, command: str):
        if self.strict_unknown_commands:
            raise SimulatorBackendError(f"Unsupported simulator {operation}: {command}")
        return "0"

    def _waveform_preamble(self) -> str:
        self._validate_waveform_points()
        x_increment = self._waveform_x_increment()
        x_origin = self._waveform_x_origin()
        y_origin = self._signal_center_v(self.waveform_source)
        if self.waveform_format == "WORD":
            return (
                f"1,0,{self.waveform_points},1,{x_increment:.12E},"
                f"{x_origin:.12E},0,{self._word_y_increment():.12E},"
                f"{y_origin:.12E},32768"
            )
        return (
            f"0,0,{self.waveform_points},1,{x_increment:.12E},"
            f"{x_origin:.12E},0,{self._byte_y_increment():.12E},"
            f"{y_origin:.12E},128"
        )

    def _measurement_value(self, command: str) -> str:
        parsed = self._parse_measurement_command(command)
        if parsed is None:
            return self._handle_unknown("query", command)

        item, channel, reference_channel, args = parsed
        self._validate_channel(channel)
        if reference_channel is not None:
            self._validate_channel(reference_channel)
        if channel in self.invalid_measurement_channels:
            return _INVALID_MEASUREMENT_SENTINEL
        if (
            reference_channel is not None
            and reference_channel in self.invalid_measurement_channels
        ):
            return _INVALID_MEASUREMENT_SENTINEL
        if not self.channel_display.get(channel, True):
            return _INVALID_MEASUREMENT_SENTINEL
        if reference_channel is not None and not self.channel_display.get(
            reference_channel, True
        ):
            return _INVALID_MEASUREMENT_SENTINEL

        if item == "time_at_value":
            level = float(args["level"])
            signal = self._signal(channel)
            if level < signal["minimum"] or level > signal["maximum"]:
                return _INVALID_MEASUREMENT_SENTINEL
        if self._measurement_is_invalid(item, channel, reference_channel, args):
            return _INVALID_MEASUREMENT_SENTINEL

        value = self._measurement_numeric_value(item, channel, reference_channel, args)
        return f"{value:.6E}"

    def _validate_waveform_points(self) -> None:
        if self.waveform_points not in _SUPPORTED_WAVEFORM_POINTS:
            if self.strict_unknown_commands:
                raise SimulatorBackendError(
                    f"Unsupported simulator waveform point count: {self.waveform_points}"
                )
            self.waveform_points = 1000
        if self.waveform_points > self._capabilities.safe_max_waveform_points:
            raise SimulatorBackendError(
                "Unsupported simulator waveform point count for model "
                f"{self.model}: {self.waveform_points}"
            )

    def _waveform_window_s(self) -> float:
        return 10.0 * self.timebase_scale

    def _waveform_x_increment(self) -> float:
        return self._waveform_window_s() / self.waveform_points

    def _waveform_x_origin(self) -> float:
        return self.timebase_position - self._waveform_window_s() / 2.0

    def _waveform_voltage_at_index(self, index: int) -> float:
        time_s = self._waveform_x_origin() + index * self._waveform_x_increment()
        acquisition_type = self.acquisition_type.upper()
        if acquisition_type.startswith("HRES"):
            return sum(
                self._raw_waveform_voltage_at_index(neighbor, noise_scale=0.5)
                for neighbor in (
                    max(0, index - 1),
                    index,
                    min(self.waveform_points - 1, index + 1),
                )
            ) / 3.0
        if acquisition_type.startswith("PEAK"):
            base = self._raw_waveform_voltage_at_index(index)
            signal = self._signal(self.waveform_source)
            envelope = max(signal["noise_rms"] * 2.0, signal["vpp"] * 0.01)
            return base + (envelope if index % 2 == 0 else -envelope)
        return self._raw_waveform_voltage_at_index(index)

    def _raw_waveform_voltage_at_index(
        self, index: int, *, noise_scale: float | None = None
    ) -> float:
        time_s = self._waveform_x_origin() + index * self._waveform_x_increment()
        physical_time_s = time_s + self._trigger_time_offset_s()
        return self._signal_voltage(
            self.waveform_source,
            physical_time_s,
            index=index,
            noise_scale=self._acquisition_noise_scale()
            if noise_scale is None
            else noise_scale,
        )

    def _byte_y_increment(self) -> float:
        return self.channel_scale.get(self.waveform_source, 1.0) / 50.0

    def _word_y_increment(self) -> float:
        return self.channel_scale.get(self.waveform_source, 1.0) / 10000.0

    def _encode_byte_sample(self, voltage: float) -> int:
        raw = round(
            (voltage - self._signal_center_v(self.waveform_source))
            / self._byte_y_increment()
            + 128
        )
        return max(0, min(255, raw))

    def _encode_word_sample(self, voltage: float) -> int:
        raw = round(
            (voltage - self._signal_center_v(self.waveform_source))
            / self._word_y_increment()
            + 32768
        )
        return max(0, min(65535, raw))

    def _signal(self, channel: int) -> dict[str, float | str]:
        configured = self.signals.get(channel, self._default_signal(channel))
        center = self._signal_center_v(channel)
        vpp = configured.vpp_v
        amplitude = vpp / 2.0
        frequency = configured.frequency_hz
        period = math.inf if frequency == 0 else 1.0 / frequency
        return {
            "shape": configured.shape,
            "frequency": frequency,
            "period": period,
            "phase_deg": configured.phase_deg,
            "center": center,
            "vpp": vpp,
            "amplitude": amplitude,
            "minimum": center - amplitude,
            "maximum": center + amplitude,
            "noise_rms": configured.noise_rms_v,
        }

    def _signal_center_v(self, channel: int) -> float:
        configured = self.signals.get(channel, self._default_signal(channel))
        return configured.offset_v + self.channel_offset.get(channel, 0.0)

    def _default_signal(self, channel: int) -> SimulatedSignal:
        return SimulatedSignal(
            shape="sine",
            frequency_hz=_SIGNAL_FREQUENCY_HZ,
            vpp_v=0.5 * channel,
            offset_v=0.0,
            phase_deg=(channel - 1) * 45.0,
            noise_rms_v=0.0,
        )

    def _signal_voltage(
        self,
        channel: int,
        time_s: float,
        *,
        index: int | None = None,
        noise_scale: float = 1.0,
    ) -> float:
        signal = self._signal(channel)
        value = self._nominal_signal_voltage(signal, time_s)
        if signal["noise_rms"] > 0 or signal["shape"] == "noise":
            value += signal["noise_rms"] * noise_scale * self._deterministic_noise(
                channel, time_s, index
            )
        return value

    def _nominal_signal_voltage(
        self, signal: dict[str, float | str], time_s: float
    ) -> float:
        shape = str(signal["shape"])
        if shape == "dc":
            return signal["center"]
        if shape == "noise":
            return signal["center"]
        frequency = signal["frequency"]
        if frequency <= 0:
            return signal["center"]
        phase_cycles = (frequency * time_s + signal["phase_deg"] / 360.0) % 1.0
        if shape == "sine":
            return signal["center"] + signal["amplitude"] * math.sin(
                2.0 * math.pi * phase_cycles
            )
        if shape == "square":
            return signal["center"] + (
                signal["amplitude"] if phase_cycles < 0.5 else -signal["amplitude"]
            )
        if shape == "ramp":
            return signal["center"] + signal["vpp"] * phase_cycles - signal["amplitude"]
        raise SimulatorBackendError(f"Unsupported simulator signal shape: {shape}")

    def _measurement_numeric_value(
        self,
        item: str,
        channel: int,
        reference_channel: int | None,
        args: dict[str, float],
    ) -> float:
        signal = self._signal(channel)
        frequency = signal["frequency"]
        period = signal["period"]
        amplitude = signal["amplitude"]
        window_s = self._waveform_window_s()
        cycles = frequency * window_s
        if self.acquisition_type.upper().startswith("PEAK"):
            envelope = max(signal["noise_rms"] * 2.0, signal["vpp"] * 0.01)
            if item == "vpp":
                return signal["vpp"] + 2.0 * envelope
            if item == "amplitude":
                return signal["amplitude"] + envelope
            if item in {"minimum", "base"}:
                return signal["minimum"] - envelope
            if item in {"maximum", "top"}:
                return signal["maximum"] + envelope

        if item in {"vpp", "amplitude"}:
            return signal["vpp"]
        if item == "frequency":
            return frequency
        if item == "period":
            return period
        if item == "vavg":
            return signal["center"]
        if item == "vrms":
            return self._vrms(signal)
        if item == "ac_rms":
            return self._ac_rms(signal)
        if item in {"minimum", "base"}:
            return signal["minimum"]
        if item in {"maximum", "top"}:
            return signal["maximum"]
        if item == "overshoot" or item == "preshoot":
            return 0.0
        if item == "x_at_max":
            return self._edge_time(channel, 0.25, 1)
        if item == "x_at_min":
            return self._edge_time(channel, 0.75, 1)
        if item in {"rise_time", "fall_time"}:
            if signal["shape"] == "square":
                return period / 100.0
            if signal["shape"] == "ramp":
                return period
            return 0.8 / (2.0 * math.pi * frequency)
        if item in {"positive_width", "negative_width"}:
            return period / 2.0
        if item in {"duty_cycle", "negative_duty_cycle"}:
            return 50.0
        if item == "area":
            return signal["center"] * window_s
        if item in {"positive_edges", "negative_edges"}:
            return float(max(1, int(round(cycles))))
        if item in {"positive_pulses", "negative_pulses"}:
            return float(max(1, int(math.floor(cycles))))
        if item == "y_at_x":
            return self._signal_voltage(channel, float(args["time_s"]))
        if item == "time_at_edge":
            occurrence = int(args["occurrence"])
            phase = 0.0 if occurrence > 0 else 0.5
            return self._edge_time(channel, phase, abs(occurrence))
        if item == "time_at_value":
            return self._time_at_value(
                channel,
                level=float(args["level"]),
                occurrence=int(args["occurrence"]),
            )
        if item == "phase" and reference_channel is not None:
            return self._phase_difference_deg(channel, reference_channel)
        if item == "delay" and reference_channel is not None:
            return (
                self._phase_difference_deg(channel, reference_channel)
                / 360.0
                / frequency
            )
        raise SimulatorBackendError(f"Unsupported simulator measurement query item: {item}")

    def _phase_difference_deg(self, channel: int, reference_channel: int) -> float:
        return (
            self._signal(reference_channel)["phase_deg"]
            - self._signal(channel)["phase_deg"]
        )

    def _edge_time(self, channel: int, phase_cycles: float, occurrence: int) -> float:
        signal = self._signal(channel)
        channel_phase_cycles = signal["phase_deg"] / 360.0
        return (
            phase_cycles + occurrence - 1 - channel_phase_cycles
        ) / signal["frequency"]

    def _time_at_value(self, channel: int, *, level: float, occurrence: int) -> float:
        signal = self._signal(channel)
        normalized = (level - signal["center"]) / signal["amplitude"]
        normalized = max(-1.0, min(1.0, normalized))
        angle = math.asin(normalized)
        if occurrence < 0:
            angle = math.pi - angle
        phase_cycles = (angle / (2.0 * math.pi)) % 1.0
        return self._edge_time(channel, phase_cycles, abs(occurrence))

    def _measurement_is_invalid(
        self,
        item: str,
        channel: int,
        reference_channel: int | None,
        args: dict[str, float],
    ) -> bool:
        if item in _PAIR_MEASUREMENT_ITEMS:
            if reference_channel is None:
                return True
            return not self._has_timing_signal(channel) or not self._has_timing_signal(
                reference_channel
            )
        if item not in _TIMING_MEASUREMENT_ITEMS:
            return False
        if not self._has_timing_signal(channel):
            return True
        signal = self._signal(channel)
        if signal["frequency"] * self._waveform_window_s() < 1.0:
            return True
        if item == "time_at_value":
            level = float(args["level"])
            if level <= signal["minimum"] or level >= signal["maximum"]:
                return True
        if item in {"time_at_edge", "time_at_value"}:
            occurrence = abs(int(args["occurrence"]))
            visible_cycles = int(
                math.floor(float(signal["frequency"]) * self._waveform_window_s())
            )
            if occurrence > max(1, visible_cycles):
                return True
        return False

    def _has_timing_signal(self, channel: int) -> bool:
        signal = self._signal(channel)
        return (
            signal["shape"] not in {"dc", "noise"}
            and signal["frequency"] > 0.0
            and signal["vpp"] > 1e-12
        )

    def _ac_rms(self, signal: dict[str, float | str]) -> float:
        amplitude = signal["amplitude"]
        if signal["shape"] == "dc":
            return 0.0
        if signal["shape"] == "square":
            return amplitude
        if signal["shape"] == "ramp":
            return amplitude / math.sqrt(3.0)
        if signal["shape"] == "noise":
            return signal["noise_rms"]
        return amplitude / math.sqrt(2.0)

    def _vrms(self, signal: dict[str, float | str]) -> float:
        return math.hypot(signal["center"], self._ac_rms(signal))

    def _deterministic_noise(
        self, channel: int, time_s: float, index: int | None
    ) -> float:
        index_value = 0 if index is None else index
        seed = (
            channel * 12.9898
            + index_value * 78.233
            + math.floor(time_s * 1.0e9) * 0.000001
        )
        return 2.0 * (math.sin(seed) * 43758.5453 % 1.0) - 1.0

    def _acquisition_noise_scale(self) -> float:
        if self.acquisition_type.upper().startswith("AVER"):
            return 1.0 / math.sqrt(max(1, self.acquisition_count))
        return 1.0

    def _trigger_time_offset_s(self) -> float:
        if self.trigger_mode.upper() != "EDGE":
            return 0.0
        if not self._has_timing_signal(self.trigger_source):
            return 0.0
        crossing = self._trigger_crossing_time_s()
        return 0.0 if crossing is None else crossing

    def _trigger_crossing_time_s(self) -> float | None:
        signal = self._signal(self.trigger_source)
        level = self.trigger_level
        if level <= signal["minimum"] or level >= signal["maximum"]:
            return None
        slope = self.trigger_slope.upper()
        if slope in {"EITHER", "EITH"}:
            candidates = tuple(
                candidate
                for candidate in (
                    self._trigger_crossing_time_for_slope(signal, level, positive=True),
                    self._trigger_crossing_time_for_slope(signal, level, positive=False),
                )
                if candidate is not None
            )
            if not candidates:
                return None
            return min(candidates, key=abs)
        if slope in {"ALTERNATE", "ALT"}:
            positive = self.trigger_alternate_count % 2 == 1
        elif slope in {"NEGATIVE", "NEG"}:
            positive = False
        else:
            positive = True
        return self._trigger_crossing_time_for_slope(signal, level, positive=positive)

    def _trigger_crossing_time_for_slope(
        self, signal: dict[str, float | str], level: float, *, positive: bool
    ) -> float | None:
        if signal["shape"] == "sine":
            normalized = (level - signal["center"]) / signal["amplitude"]
            normalized = max(-1.0, min(1.0, normalized))
            angle = math.asin(normalized)
            if not positive:
                angle = math.pi - angle
            phase_cycles = (angle / (2.0 * math.pi)) % 1.0
        elif signal["shape"] == "square":
            phase_cycles = 0.0 if positive else 0.5
        elif signal["shape"] == "ramp":
            if not positive:
                return None
            phase_cycles = (level - signal["minimum"]) / signal["vpp"]
        else:
            return None
        return (
            phase_cycles - signal["phase_deg"] / 360.0
        ) / signal["frequency"]

    def _parse_measurement_command(
        self, command: str
    ) -> tuple[str, int, int | None, dict[str, float]] | None:
        pair_match = re.fullmatch(
            r":MEASure:(PHASe|DELay)\?\s+(?:AUTO,)?CHANnel(\d+),CHANnel(\d+)",
            command,
            flags=re.IGNORECASE,
        )
        if pair_match:
            raw_item, channel, reference = pair_match.groups()
            item = "phase" if raw_item.upper() == "PHASE" else "delay"
            return item, int(channel), int(reference), {}

        y_at_x_match = re.fullmatch(
            r":MEASure:VTIMe\?\s+([^,]+),CHANnel(\d+)",
            command,
            flags=re.IGNORECASE,
        )
        if y_at_x_match:
            time_s, channel = y_at_x_match.groups()
            return "y_at_x", int(channel), None, {"time_s": float(time_s)}

        edge_match = re.fullmatch(
            r":MEASure:TEDGe\?\s+([+-]?\d+),CHANnel(\d+)",
            command,
            flags=re.IGNORECASE,
        )
        if edge_match:
            occurrence, channel = edge_match.groups()
            return "time_at_edge", int(channel), None, {"occurrence": int(occurrence)}

        value_match = re.fullmatch(
            r":MEASure:TVALue\?\s+([^,]+),([+-]?\d+),CHANnel(\d+)",
            command,
            flags=re.IGNORECASE,
        )
        if value_match:
            level, occurrence, channel = value_match.groups()
            return (
                "time_at_value",
                int(channel),
                None,
                {"level": float(level), "occurrence": int(occurrence)},
            )

        single_match = re.fullmatch(
            r":MEASure:([A-Za-z]+)\?\s+(?:DISPlay,(?:(AC|DC),)?)?CHANnel(\d+)",
            command,
            flags=re.IGNORECASE,
        )
        if not single_match:
            return None

        raw_item, rms_mode, channel = single_match.groups()
        item = self._single_measurement_item(raw_item, rms_mode)
        if item is None:
            return None
        return item, int(channel), None, {}

    def _single_measurement_item(self, raw_item: str, rms_mode: str | None) -> str | None:
        normalized = raw_item.upper()
        items = {
            "VPP": "vpp",
            "FREQUENCY": "frequency",
            "PERIOD": "period",
            "VAVERAGE": "vavg",
            "VMIN": "minimum",
            "VMAX": "maximum",
            "XMAX": "x_at_max",
            "XMIN": "x_at_min",
            "RISETIME": "rise_time",
            "FALLTIME": "fall_time",
            "VAMPLITUDE": "amplitude",
            "VTOP": "top",
            "VBASE": "base",
            "OVERSHOOT": "overshoot",
            "PRESHOOT": "preshoot",
            "PWIDTH": "positive_width",
            "NWIDTH": "negative_width",
            "DUTYCYCLE": "duty_cycle",
            "NDUTY": "negative_duty_cycle",
            "AREA": "area",
            "PEDGES": "positive_edges",
            "NEDGES": "negative_edges",
            "PPULSES": "positive_pulses",
            "NPULSES": "negative_pulses",
        }
        if normalized == "VRMS":
            return "ac_rms" if rms_mode and rms_mode.upper() == "AC" else "vrms"
        return items.get(normalized)

    def _apply_measurement_install(self, command: str) -> bool:
        match = re.fullmatch(r":MEASure:([A-Za-z]+)", command, flags=re.IGNORECASE)
        if not match:
            return False
        item = self._single_measurement_item(match.group(1), None)
        if item is None:
            return False
        self.measurement_statistics_items.append(item)
        return True

    def _measurement_statistics_results(self) -> str:
        items = self.measurement_statistics_items or ["vpp"]
        parts: list[str] = []
        for item in items:
            value = self._measurement_numeric_value(item, self.measurement_source, None, {})
            minimum = value * 0.98
            maximum = value * 1.02
            stddev = abs(value) * 0.005
            parts.extend(
                [
                    item,
                    f"{value:.6E}",
                    f"{minimum:.6E}",
                    f"{maximum:.6E}",
                    f"{value:.6E}",
                    f"{stddev:.6E}",
                    "16",
                ]
            )
        return ",".join(parts)

    def _apply_fft_write(self, command: str) -> bool:
        match = re.fullmatch(r":FUNCtion(\d+):([A-Za-z0-9]+)(?::([A-Za-z]+))?\s+(.+)", command, flags=re.IGNORECASE)
        if not match:
            return False
        function = int(match.group(1))
        key = self.fft_functions.setdefault(
            function,
            {
                "operation": "FFT",
                "source": 1,
                "units": "DECibel",
                "window": "HANNing",
                "center": 0.0,
                "span": 1.0e6,
                "display": False,
            },
        )
        primary, secondary, value = match.group(2).upper(), (match.group(3) or "").upper(), match.group(4)
        if primary == "OPERATION":
            key["operation"] = value.upper()
        elif primary == "SOURCE1":
            key["source"] = self._validate_channel(int(value.rsplit("CHANnel", 1)[1]))
        elif primary == "DISPLAY":
            key["display"] = value.upper() == "ON"
        elif primary == "FFT" and secondary == "VTYPE":
            key["units"] = value
        elif primary == "FFT" and secondary == "WINDOW":
            key["window"] = value
        elif primary == "FFT" and secondary == "CENTER":
            key["center"] = float(value)
        elif primary == "FFT" and secondary == "SPAN":
            key["span"] = float(value)
        else:
            return False
        return True

    def _query_fft(self, command: str) -> str | None:
        match = re.fullmatch(r":FUNCtion(\d+):([A-Za-z0-9]+)(?::([A-Za-z]+))?\?", command, flags=re.IGNORECASE)
        if not match:
            return None
        function = int(match.group(1))
        state = self.fft_functions.setdefault(
            function,
            {
                "operation": "FFT",
                "source": 1,
                "units": "DECibel",
                "window": "HANNing",
                "center": 0.0,
                "span": 1.0e6,
                "display": False,
            },
        )
        primary, secondary = match.group(2).upper(), (match.group(3) or "").upper()
        if primary == "OPERATION":
            return str(state["operation"])
        if primary == "SOURCE1":
            return f"CHANnel{state['source']}"
        if primary == "DISPLAY":
            return "1" if state["display"] else "0"
        if primary == "FFT" and secondary == "VTYPE":
            return str(state["units"])
        if primary == "FFT" and secondary == "WINDOW":
            return str(state["window"])
        if primary == "FFT" and secondary == "CENTER":
            return f"{float(state['center']):.12g}"
        if primary == "FFT" and secondary == "SPAN":
            return f"{float(state['span']):.12g}"
        return None

    def _apply_channel_write(self, command: str) -> bool:
        channel = _extract_channel(command)
        if channel is None:
            return False
        channel = self._validate_channel(channel)
        upper = command.upper()
        value = command.rsplit(" ", 1)[1] if " " in command else ""
        if ":DISPLAY " in upper:
            self.channel_display[channel] = upper.endswith(" ON")
        elif ":SCALE " in upper:
            self.channel_scale[channel] = float(value)
        elif ":OFFSET " in upper:
            self.channel_offset[channel] = float(value)
        elif ":COUPLING " in upper:
            self.channel_coupling[channel] = value.upper()
        elif ":PROBE " in upper:
            self.channel_probe[channel] = float(value)
        elif ":BWLIMIT " in upper:
            self.channel_bandwidth_limit[channel] = upper.endswith(" ON")
        else:
            return False
        return True

    def _query_channel(self, command: str) -> str | None:
        channel = _extract_channel(command)
        if channel is None:
            return None
        channel = self._validate_channel(channel)
        upper = command.upper()
        if ":DISPLAY?" in upper:
            return "1" if self.channel_display.get(channel, True) else "0"
        if ":SCALE?" in upper:
            return f"{self.channel_scale.get(channel, 1.0):.12g}"
        if ":OFFSET?" in upper:
            return f"{self.channel_offset.get(channel, 0.0):.12g}"
        if ":COUPLING?" in upper:
            return self.channel_coupling.get(channel, "DC")
        if ":PROBE?" in upper:
            return f"{self.channel_probe.get(channel, 10.0):.12g}"
        if ":BWLIMIT?" in upper:
            return "1" if self.channel_bandwidth_limit.get(channel, False) else "0"
        return None

    def _validate_channel(self, channel: int) -> int:
        if channel < 1 or channel > self._capabilities.analog_channels:
            raise SimulatorBackendError(
                f"Simulator model {self.model} has "
                f"{self._capabilities.analog_channels} analog channels; "
                f"CH{channel} is not available."
            )
        return channel


def _extract_channel(command: str) -> int | None:
    marker = ":CHANnel"
    if marker not in command:
        return None
    remainder = command.split(marker, 1)[1]
    digits = []
    for char in remainder:
        if char.isdigit():
            digits.append(char)
        else:
            break
    return int("".join(digits)) if digits else None


def _coerce_simulated_signal(
    signal: SimulatedSignal | dict[str, float | str],
) -> SimulatedSignal:
    if isinstance(signal, SimulatedSignal):
        return signal
    return SimulatedSignal(**signal)


def _parse_scpi_number(value: str) -> float:
    parts = value.strip().split()
    if not parts:
        raise SimulatorBackendError("Missing numeric SCPI parameter.")
    if len(parts) != 1:
        raise SimulatorBackendError(
            f"SCPI numeric parameters must not include unit suffixes: {value!r}"
        )
    return float(parts[0])


_SCREENSHOT_WIDTH = 480
_SCREENSHOT_HEIGHT = 272
_PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"

_FONT_5X7 = {
    " ": ("00000", "00000", "00000", "00000", "00000", "00000", "00000"),
    "-": ("00000", "00000", "00000", "11111", "00000", "00000", "00000"),
    "0": ("01110", "10001", "10011", "10101", "11001", "10001", "01110"),
    "1": ("00100", "01100", "00100", "00100", "00100", "00100", "01110"),
    "2": ("01110", "10001", "00001", "00010", "00100", "01000", "11111"),
    "3": ("11110", "00001", "00001", "01110", "00001", "00001", "11110"),
    "4": ("00010", "00110", "01010", "10010", "11111", "00010", "00010"),
    "5": ("11111", "10000", "10000", "11110", "00001", "00001", "11110"),
    "6": ("01110", "10000", "10000", "11110", "10001", "10001", "01110"),
    "7": ("11111", "00001", "00010", "00100", "01000", "01000", "01000"),
    "8": ("01110", "10001", "10001", "01110", "10001", "10001", "01110"),
    "9": ("01110", "10001", "10001", "01111", "00001", "00001", "01110"),
    "A": ("01110", "10001", "10001", "11111", "10001", "10001", "10001"),
    "B": ("11110", "10001", "10001", "11110", "10001", "10001", "11110"),
    "C": ("01110", "10001", "10000", "10000", "10000", "10001", "01110"),
    "D": ("11110", "10001", "10001", "10001", "10001", "10001", "11110"),
    "E": ("11111", "10000", "10000", "11110", "10000", "10000", "11111"),
    "F": ("11111", "10000", "10000", "11110", "10000", "10000", "10000"),
    "G": ("01110", "10001", "10000", "10111", "10001", "10001", "01110"),
    "H": ("10001", "10001", "10001", "11111", "10001", "10001", "10001"),
    "I": ("01110", "00100", "00100", "00100", "00100", "00100", "01110"),
    "J": ("00111", "00010", "00010", "00010", "00010", "10010", "01100"),
    "K": ("10001", "10010", "10100", "11000", "10100", "10010", "10001"),
    "L": ("10000", "10000", "10000", "10000", "10000", "10000", "11111"),
    "M": ("10001", "11011", "10101", "10101", "10001", "10001", "10001"),
    "N": ("10001", "11001", "10101", "10011", "10001", "10001", "10001"),
    "O": ("01110", "10001", "10001", "10001", "10001", "10001", "01110"),
    "P": ("11110", "10001", "10001", "11110", "10000", "10000", "10000"),
    "Q": ("01110", "10001", "10001", "10001", "10101", "10010", "01101"),
    "R": ("11110", "10001", "10001", "11110", "10100", "10010", "10001"),
    "S": ("01111", "10000", "10000", "01110", "00001", "00001", "11110"),
    "T": ("11111", "00100", "00100", "00100", "00100", "00100", "00100"),
    "U": ("10001", "10001", "10001", "10001", "10001", "10001", "01110"),
    "V": ("10001", "10001", "10001", "10001", "10001", "01010", "00100"),
    "W": ("10001", "10001", "10001", "10101", "10101", "10101", "01010"),
    "X": ("10001", "10001", "01010", "00100", "01010", "10001", "10001"),
    "Y": ("10001", "10001", "01010", "00100", "00100", "00100", "00100"),
    "Z": ("11111", "00001", "00010", "00100", "01000", "10000", "11111"),
}


def _simulated_screenshot_png(model: str, *, white_background: bool) -> bytes:
    background = (255, 255, 255) if white_background else (0, 0, 0)
    grid = (210, 210, 210) if white_background else (42, 42, 42)
    axis = (160, 160, 160) if white_background else (72, 72, 72)
    text = (28, 32, 38) if white_background else (244, 244, 244)
    ch1 = (156, 112, 0) if white_background else (255, 214, 0)
    ch2 = (0, 120, 132) if white_background else (0, 220, 235)

    pixels = bytearray(background * (_SCREENSHOT_WIDTH * _SCREENSHOT_HEIGHT))

    for x in range(40, _SCREENSHOT_WIDTH, 40):
        _draw_vertical_line(pixels, x, grid if x != _SCREENSHOT_WIDTH // 2 else axis)
    for y in range(34, _SCREENSHOT_HEIGHT, 34):
        _draw_horizontal_line(pixels, y, grid if y != _SCREENSHOT_HEIGHT // 2 else axis)

    _draw_waveform(pixels, ch1, center_y=116, amplitude=42, phase=0.0)
    _draw_waveform(pixels, ch2, center_y=158, amplitude=36, phase=math.pi / 4.0)
    _draw_text(pixels, 12, 10, f"SIM {model.upper()}", text, scale=2)
    _draw_text(pixels, 12, 244, "CH1", ch1, scale=2)
    _draw_text(pixels, 66, 244, "CH2", ch2, scale=2)
    return _encode_rgb_png(_SCREENSHOT_WIDTH, _SCREENSHOT_HEIGHT, pixels)


def _encode_rgb_png(width: int, height: int, pixels: bytearray) -> bytes:
    stride = width * 3
    raw = bytearray()
    for y in range(height):
        raw.append(0)
        start = y * stride
        raw.extend(pixels[start : start + stride])
    return b"".join(
        (
            _PNG_SIGNATURE,
            _png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)),
            _png_chunk(b"IDAT", zlib.compress(bytes(raw), level=9)),
            _png_chunk(b"IEND", b""),
        )
    )


def _png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    checksum = binascii.crc32(chunk_type)
    checksum = binascii.crc32(data, checksum) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + chunk_type + data + struct.pack(">I", checksum)


def _draw_vertical_line(pixels: bytearray, x: int, color: tuple[int, int, int]) -> None:
    for y in range(_SCREENSHOT_HEIGHT):
        _set_pixel(pixels, x, y, color)


def _draw_horizontal_line(pixels: bytearray, y: int, color: tuple[int, int, int]) -> None:
    for x in range(_SCREENSHOT_WIDTH):
        _set_pixel(pixels, x, y, color)


def _draw_waveform(
    pixels: bytearray,
    color: tuple[int, int, int],
    *,
    center_y: int,
    amplitude: int,
    phase: float,
) -> None:
    previous: tuple[int, int] | None = None
    for x in range(24, _SCREENSHOT_WIDTH - 16):
        angle = (x - 24) / (_SCREENSHOT_WIDTH - 40) * 2.0 * math.pi * 2.4 + phase
        y = round(center_y - amplitude * math.sin(angle))
        if previous is not None:
            _draw_line(pixels, previous[0], previous[1], x, y, color)
            _draw_line(pixels, previous[0], previous[1] + 1, x, y + 1, color)
        previous = (x, y)


def _draw_line(
    pixels: bytearray,
    x0: int,
    y0: int,
    x1: int,
    y1: int,
    color: tuple[int, int, int],
) -> None:
    dx = abs(x1 - x0)
    dy = -abs(y1 - y0)
    sx = 1 if x0 < x1 else -1
    sy = 1 if y0 < y1 else -1
    error = dx + dy
    while True:
        _set_pixel(pixels, x0, y0, color)
        if x0 == x1 and y0 == y1:
            return
        doubled = 2 * error
        if doubled >= dy:
            error += dy
            x0 += sx
        if doubled <= dx:
            error += dx
            y0 += sy


def _draw_text(
    pixels: bytearray,
    x: int,
    y: int,
    text: str,
    color: tuple[int, int, int],
    *,
    scale: int,
) -> None:
    cursor = x
    for char in text:
        glyph = _FONT_5X7.get(char, _FONT_5X7["-"])
        for row_index, row in enumerate(glyph):
            for column_index, value in enumerate(row):
                if value == "1":
                    _fill_rect(
                        pixels,
                        cursor + column_index * scale,
                        y + row_index * scale,
                        scale,
                        scale,
                        color,
                    )
        cursor += 6 * scale


def _fill_rect(
    pixels: bytearray,
    x: int,
    y: int,
    width: int,
    height: int,
    color: tuple[int, int, int],
) -> None:
    for row in range(y, y + height):
        for column in range(x, x + width):
            _set_pixel(pixels, column, row, color)


def _set_pixel(pixels: bytearray, x: int, y: int, color: tuple[int, int, int]) -> None:
    if x < 0 or x >= _SCREENSHOT_WIDTH or y < 0 or y >= _SCREENSHOT_HEIGHT:
        return
    offset = (y * _SCREENSHOT_WIDTH + x) * 3
    pixels[offset : offset + 3] = bytes(color)
